# Generated by Django 4.2.19 on 2025-03-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strategy',
            new_name='Strategies',
        ),
    ]
