# Generated by Django 4.2.19 on 2025-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_delete_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
