# Generated by Django 4.2.19 on 2025-03-29 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_exchange_alter_symbols_exchange'),
        ('strategies', '0004_strategy_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
            options={
                'unique_together': {('strategy', 'symbol')},
            },
        ),
    ]
