# Generated by Django 4.2.19 on 2025-03-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_strategysymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysymbol',
            name='slot_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='strategysymbol',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
