# Generated by Django 4.2.19 on 2025-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_strategysymbol_slot_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategysymbol',
            old_name='is_active',
            new_name='is_active_long',
        ),
        migrations.AddField(
            model_name='strategysymbol',
            name='is_active_short',
            field=models.BooleanField(default=False),
        ),
    ]
