# Generated by Django 4.2.19 on 2025-04-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_exchange_alter_symbols_exchange'),
        ('strategies', '0007_rename_is_active_strategysymbol_is_active_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelatedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.exchange')),
                ('symbol_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_first', to='symbols.symbols')),
                ('symbol_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_second', to='symbols.symbols')),
            ],
            options={
                'unique_together': {('exchange', 'symbol_1', 'symbol_2')},
            },
        ),
    ]
