# Generated by Django 4.2.19 on 2025-04-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_correlatedpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysymbol',
            name='correlated_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.correlatedpair'),
        ),
    ]
