# Generated by Django 4.2.19 on 2025-04-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_exchange_alter_symbols_exchange'),
        ('strategies', '0009_strategysymbol_correlated_pair'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategysymbol',
            unique_together={('strategy', 'symbol', 'correlated_pair')},
        ),
    ]
