# Generated by Django 4.2.19 on 2025-04-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0008_symbols_slot_free'),
        ('strategies', '0010_alter_strategysymbol_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategysymbol',
            unique_together={('strategy', 'symbol')},
        ),
        migrations.RemoveField(
            model_name='strategysymbol',
            name='slot_free',
        ),
    ]
