# Generated by Django 4.2.19 on 2025-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0008_symbols_slot_free'),
        ('strategies', '0011_alter_strategysymbol_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategysymbol',
            unique_together={('strategy', 'symbol', 'correlated_pair')},
        ),
    ]
