# Generated by Django 4.2.19 on 2025-04-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0012_alter_strategysymbol_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysymbol',
            name='slot_free',
            field=models.BooleanField(default=True),
        ),
    ]
