# Generated by Django 4.2.15 on 2024-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('instrument', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
            ],
        ),
    ]
