# Generated by Django 4.2.15 on 2024-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symbol',
            new_name='Symbols',
        ),
    ]
