# Generated by Django 4.2.15 on 2024-08-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_rename_symbol_symbols'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbols',
            options={'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterModelTable(
            name='symbols',
            table='symbol',
        ),
    ]
