# Generated by Django 4.2.15 on 2024-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0003_alter_symbols_options_alter_symbols_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbols',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='symbols',
            name='exchange_id',
        ),
        migrations.RemoveField(
            model_name='symbols',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='symbols',
            name='sector',
        ),
        migrations.AddField(
            model_name='symbols',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
