# Generated by Django 4.2.15 on 2024-09-02 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0004_remove_symbols_currency_remove_symbols_exchange_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
            options={
                'db_table': 'daily_price',
                'unique_together': {('symbol', 'price_date')},
            },
        ),
    ]
