# Generated by Django 4.2.15 on 2025-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0005_alter_symbols_created_date_dailyprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='exchange',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
