# Generated by Django 4.2.19 on 2025-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_exchange_alter_symbols_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='slot_free',
            field=models.BooleanField(default=True),
        ),
    ]
