# Generated by Django 4.2.19 on 2025-06-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0009_broker_symbols_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
