# Generated by Django 4.2.19 on 2025-06-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0010_broker_api_key_broker_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='symbols',
            name='short',
            field=models.BooleanField(default=False),
        ),
    ]
