# Generated by Django 4.2.19 on 2025-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0011_symbols_long_symbols_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
