# Generated by Django 4.2.19 on 2025-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0012_broker_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='adj_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
