# Generated by Django 4.2.19 on 2025-03-27 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0004_strategy_parameters'),
        ('symbols', '0007_exchange_alter_symbols_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT'), ('EXIT', 'EXIT')], max_length=5)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('profit_loss', models.FloatField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestingstrategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('profit_loss', models.FloatField()),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_stats', to='backtesting.backtestingstrategy')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('total_profit_loss', models.FloatField()),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_stats', to='backtesting.backtestingstrategy')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_statistics', to='strategies.strategy')),
            ],
        ),
    ]
