# Generated by Django 4.2.19 on 2025-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_backtestingstrategy_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
