# Generated by Django 4.2.19 on 2025-03-27 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_alter_tradehistory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestingstrategy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
