# Generated by Django 4.2.19 on 2025-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0004_backtestingstrategy_name_tradehistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
