# Generated by Django 4.2.19 on 2025-03-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0005_tradehistory_max_drawdown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystatistics',
            old_name='max_drawdown',
            new_name='average_holding_period',
        ),
        migrations.RenameField(
            model_name='strategystatistics',
            old_name='sharpe_ratio',
            new_name='average_max_drawdown',
        ),
        migrations.RenameField(
            model_name='symbolstatistics',
            old_name='max_drawdown',
            new_name='average_holding_period',
        ),
        migrations.AddField(
            model_name='strategystatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='strategystatistics',
            name='roi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbolstatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='symbolstatistics',
            name='average_max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbolstatistics',
            name='roi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategystatistics',
            name='total_profit_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategystatistics',
            name='total_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategystatistics',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbolstatistics',
            name='profit_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbolstatistics',
            name='total_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbolstatistics',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
