# Generated by Django 4.2.19 on 2025-04-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0006_rename_max_drawdown_strategystatistics_average_holding_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystatistics',
            old_name='roi',
            new_name='total_roi',
        ),
        migrations.RenameField(
            model_name='symbolstatistics',
            old_name='roi',
            new_name='total_roi',
        ),
    ]
