# Generated by Django 4.2.19 on 2025-04-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_correlatedpair'),
        ('backtesting', '0007_rename_roi_strategystatistics_total_roi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='correlated_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.correlatedpair'),
        ),
    ]
