# Generated by Django 4.2.19 on 2025-04-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_correlatedpair'),
        ('backtesting', '0009_strategystatistics_correlated_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategystatistics',
            name='correlated_pair',
        ),
        migrations.AddField(
            model_name='symbolstatistics',
            name='correlated_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.correlatedpair'),
        ),
    ]
