# Generated by Django 4.2.19 on 2025-04-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0010_remove_strategystatistics_correlated_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolstatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SHORT', 'SHORT'), ('PAIR_TRADING', 'PAIR_TRADING')], max_length=20, null=True),
        ),
    ]
