# Generated by Django 4.2.19 on 2025-04-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_exchange_alter_symbols_exchange'),
        ('backtesting', '0011_alter_symbolstatistics_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolstatistics',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols'),
        ),
    ]
