# Generated by Django 4.2.19 on 2025-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0012_alter_symbolstatistics_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SHORT', 'SHORT'), ('PAIR_TRADING', 'PAIR_TRADING')], max_length=20, null=True),
        ),
    ]
