# Generated by Django 4.2.19 on 2025-06-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0012_broker_endpoint'),
        ('backtesting', '0013_alter_strategystatistics_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestingstrategy',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='symbols.broker'),
        ),
    ]
