# Generated by Django 4.2.19 on 2025-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0014_backtestingstrategy_broker'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='backtestingstrategy',
            constraint=models.UniqueConstraint(fields=('strategy', 'broker'), name='unique_strategy_broker'),
        ),
    ]
