# Generated by Django 4.2.19 on 2025-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0015_backtestingstrategy_unique_strategy_broker'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='backtestingstrategy',
            name='unique_strategy_broker',
        ),
        migrations.AddConstraint(
            model_name='backtestingstrategy',
            constraint=models.UniqueConstraint(fields=('strategy', 'name', 'broker'), name='unique_strategy_broker'),
        ),
    ]
