# Generated by Django 4.2.19 on 2025-08-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0013_alter_dailyprice_adj_close_price'),
        ('backtesting', '0016_remove_backtestingstrategy_unique_strategy_broker_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='backtestingstrategy',
            name='unique_strategy_broker',
        ),
        migrations.AddField(
            model_name='backtestingstrategy',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_backtests', to='symbols.exchange'),
        ),
        migrations.AddField(
            model_name='strategystatistics',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_strategy_stats', to='symbols.exchange'),
        ),
        migrations.AddField(
            model_name='symbolstatistics',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_symbol_stats', to='symbols.exchange'),
        ),
        migrations.AddConstraint(
            model_name='backtestingstrategy',
            constraint=models.UniqueConstraint(fields=('strategy', 'name', 'broker', 'exchange'), name='unique_strategy_broker_exchange'),
        ),
    ]
