# Generated by Django 4.2.19 on 2025-04-11 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0008_symbols_slot_free'),
        ('strategies', '0013_strategysymbol_slot_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistoryExec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT'), ('EXIT', 'EXIT')], max_length=5)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('profit_loss', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correlated_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategies.correlatedpair')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
        ),
    ]
