# Generated by Django 4.2.19 on 2025-04-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistoryexec',
            name='bet_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
